"""init

Revision ID: 89a1568cfc1e
Revises: d7d2241aa69a
Create Date: 2022-04-17 12:52:26.923394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a1568cfc1e'
down_revision = 'd7d2241aa69a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
