"""init

Revision ID: d7d2241aa69a
Revises: 09dbdab758ad
Create Date: 2022-04-17 12:50:24.926847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7d2241aa69a'
down_revision = '09dbdab758ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
